### ISSUE TITLE
No Python 2.7 compatible release

### ISSUE THREAD

**Issue by avrahamshukron** [mfcovington/django-taggit-helpers#2]
Hi!

I noticed that you updated the code so it can be installed on Python 2.7.
The latest version on pypi though is still 3.2+ only.

Can you create a release for the latest changes with the 2.7 support?

Thanks!

**Comment by mfcovington** [comment]
Thanks for the reminder @avrahamshukron! The 2.7-compatible release is now on [PyPI](https://pypi.python.org/pypi/django-taggit-helpers/0.1.3).

**Comment by avrahamshukron** [comment]
Wow that was fast! thanks!
